### ISSUE TITLE
Suggestion: Adding `extends native` section to FAQ

### ISSUE THREAD

**Issue by HerringtonDarkholme** [Microsoft/TypeScript-wiki#103]
Extending native object has been documented in Breaking Changes section. But for new comers it seems not as discoverable as FAQ.

We already have a lot of [duplicate questions](https://github.com/Microsoft/TypeScript/search?utf8=%E2%9C%93&q=extend+Error+instanceof&type=Issues) on issue listing which qualifies extending native object as Frequently Asked.

Would be happy to submit a PR for it.

**Comment by johnnyreilly** [comment]
Good idea!

**Comment by DanielRosenwasser** [comment]
I think we'd take a PR.
