### ISSUE TITLE
Add colbyrussell as a collaborator

### ISSUE THREAD

**Issue by colbyrussell** [Microsoft/TypeScript-wiki#11]
I'd like to be able to edit the wiki.

**Comment by DanielRosenwasser** [comment]
Right now you can edit the wiki by forking it and sending a pull request. This allows us to review changes, and I always sync upstream immediately afterwards.

**Comment by DanielRosenwasser** [comment]
Sorry that GitHub has had a lot of pain points for you; not sure if it's soured the idea of contributing, but I'd still like to continue using the PR-style approach so that changes can be reviewed. Closing this for now.

**Comment by colbyrussell** [comment]
The overreliance on GitHub's features that remain half-implemented means that the value proposition for getting changes upstream is a weak one at this point.  CBA says that further work on TypeScript will be better limited to a private fork for now.  Where it makes sense to, some exceptional cases will see some changes may make their way upstream.

Chances that the wiki will get any growth or maintenance out of this, however, are pretty small.

**Comment by DanielRosenwasser** [comment]
Sorry, could you clarify what CBA is?

**Comment by colbyrussell** [comment]
Cost-benefit analysis
