### ISSUE TITLE
JSDoc-support-in-JavaScript.md appears to be out of date.

### ISSUE THREAD

**Issue by Adam-Meisen** [Microsoft/TypeScript-wiki#117]
At the time of writing this, [JSDoc-support-in-JavaScript.md](https://github.com/Microsoft/TypeScript-wiki/blob/0935714fd3c447e97e5a8a7ca7c123da9d5d9eff/JSDoc-support-in-JavaScript.md) appears to be out of date. The page explicitly states that the `@typedef` tag is not currently supported, but support for `@typedef` appears to have been added prior to version 2.0.  https://github.com/Microsoft/TypeScript/issues/7758

I would update the page myself, but I'm not familiar with what tags are currently supported, and I don't know where to look.

**Comment by mhegazy** [comment]
A PR adding the documentation would be appreciated.

**Comment by Adam-Meisen** [comment]
I'd be happy to do that, do you know where I might look find out which
JSDoc tags are currently supported?

On Apr 13, 2017 11:04 AM, "Mohamed Hegazy" <notifications@github.com> wrote:

A PR adding the documentation would be appreciated.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/TypeScript-wiki/issues/117#issuecomment-293940403>,
or mute the thread

**Comment by mhegazy** [comment]
@typedef is the only one that was added after the docs were written.

**Comment by Adam-Meisen** [comment]
Thanks, I'll get on that shortly.

**Comment by Adam-Meisen** [comment]
#118
