### ISSUE TITLE
TypeScript-wiki content doesn't mention content license

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript-wiki#13]
If I go to Special:Random page on Wikipedia right now and edit whatever I found, anyone is free to use the result under CC-BY-SA 3.0.

Under what terms is the TypeScript wiki content available?

**Comment by DanielRosenwasser** [comment]
I would think (and prefer) either CC-BY-SA or Apache 2.0. Can @jonathandturner or @mhegazy please weigh in on this?

**Comment by orta** [comment]
I'm not exactly a lawyer, but I think we should license this as CC-BY-SA, for example [azure-docs](https://github.com/MicrosoftDocs/azure-docs/blob/master/LICENSE) is that.

**Comment by orta** [comment]
Added this 👍
