### ISSUE TITLE
Design issue - Function typing inconsistency (?)

### ISSUE THREAD

**Issue by bobOnGitHub** [Microsoft/TypeScript-wiki#145]
From the Typescript web site ( https://www.typescriptlang.org/docs/handbook/functions.html ) ;

```
let myAdd: (x: number, y: number) => number =
    function(x: number, y: number): number { return x + y; };
```

....but an arrow function is not functionally the same as a "function" function - they are not the same (type of) thing.

**Comment by mhegazy** [comment]
Issue already addressed in https://github.com/Microsoft/TypeScript/issues/18749
