### ISSUE TITLE
Missing example how compile using tsconfig.json

### ISSUE THREAD

**Issue by CzBuCHi** [microsoft/TypeScript-wiki#147]
this is what im having in mind:
```
var config = { // this is generated on the fly ... or JSON.parse(readFileAsText('tsConfig.json'))
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "outDir": "./lib",
        "jsx": "react",
    },
    "compileOnSave": false,
    "include": ["src"],
    "exclude": ["lib"]
}

var emitResult = tsc.compileByConfig(config); // this line is what im missing ..
```

currently i have no idea, how to resolve all files that will be compiled...

**Comment by mhegazy** [comment]
Use `ts.parseJsonConfigFileContent` to parse the JSON object, then pass the result to `ts.createProgram`. From there you can emit the files (see [createProgram example](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-minimal-compiler)).

**Comment by orta** [comment]
Closing as this feels like a good answer 👍

**Comment by Schahen** [comment]
Can not help but notice that in the [createProgram](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-minimal-compiler) there's no examples of usage of `ts.parseJsonConfigFileContent`.

**Comment by tianzhich** [comment]
[Here](https://gist.github.com/jeremyben/4de4fdc40175d0f76892209e00ece98f) is an example of usage, in my use:

```ts
const cwd = process.cwd();
const configJSON = require(path.join(cwd, 'tsconfig.json'));

// options is ts.CompilerOptions that you can use in ts.createProgram
const { options } = ts.parseJsonConfigFileContent(configJSON, ts.sys, cwd);
```
