### ISSUE TITLE
Remove pages that duplicate handbook content

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-wiki#17]
We should just link to [handbook content](https://github.com/Microsoft/TypeScript-Handbook). When both the wiki and handbook are in flux, keeping them in sync can be a bit of a pain.

**Comment by jonathandturner** [comment]
Ideally the website would pull the handbook content directly from GitHub.  We're working on it.

**Comment by DanielRosenwasser** [comment]
Right, but this is for the wiki, not necessarily the website.
