### ISSUE TITLE
Width code examples is too big

### ISSUE THREAD

**Issue by guidojo** [Microsoft/TypeScript-wiki#176]
Hello guys,

First of all; thank you for the great examples on your website :) They really help me with some work I'm doing.

When looking to some code examples (like here: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) I have a hard time reading it, since my mouse doesn't have a horizontal scroll option. Can you introduce a rule for max 80 width in code examples? I'm willing to help realising this, just say the word :)

Guido

**Comment by mhegazy** [comment]
Sure. would be happy to take a PR for the change.
