### ISSUE TITLE
What process are you following to allow PR's to Wiki?

### ISSUE THREAD

**Issue by gep13** [Microsoft/TypeScript-wiki#2]
We have been wanting to allow edit's to our wiki for Chocolatey, but we also want to "moderate" the submissions via pull requests.  Having hunted around a bit, we hadn't found an "easy" way to do this, but it looks like you guys have.

Would it be possible for  you to explain what you did to set this up so that this GitHub repo updates the wiki on the TypeScript GitHub Site.  What process are you following?

Thanks in advance!

**Comment by mhegazy** [comment]
We just have a new repo TypeScript-wiki that is identical to TypeScript.wiki (the wiki for our repo). Locally we have a wiki git clone that has two remotes pointing to the two repos, every time we have a new change to the TypeScript-Wiki @DanielRosenwasser merges the other repo in and pushes to the two remotes.

I would not call that a good solution though :) ideally github should allow PRs to the wiki. but until this happens, we are getting by.

**Comment by DanielRosenwasser** [comment]
Basically, when you create a GitHub wiki, a new git repo is set up, with ".wiki" appended to the base repo name. For instance, I believe ours was reachable at https://GitHub.com/Microsoft/TypeScript.wiki.git

You can clone the repo and then push to a new remote (in our case it was https://GitHub.com/Microsoft/TypeScript-wiki.git). I set up that remote as `origin ` and the original as `actualwiki`.

I'm on my phone so if any of this sounds wrong or vague, feel free to point it out and I'll try to clarify.

**Comment by gep13** [comment]
Thanks for all the information @mhegazy and @DanielRosenwasser.  This definitely sounds like a workable solution to the problem.  I totally agree that this is something that @github need to make easier.

@ferventcoder what are your thoughts?  I really like the idea of being able to accept changes to the documentation for Chocolatey, but also allow us to keep a check on what changes are being submitted.

**Comment by ferventcoder** [comment]
Yep, we knew about the wiki repo, we just didn't think about pushing it to another source that would be PR-able.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco-wiki

**Comment by gep13** [comment]
Noice one!

Thanks again for your help guys!
