### ISSUE TITLE
Wiki repo not up to date

### ISSUE THREAD

**Issue by Pmyl** [Microsoft/TypeScript-wiki#201]
I would like to create a PR fixing a typo and trying to make the `What's new` better but it seems like this repo is not up to date with what I can see in the actual Typescript repo's wiki.

Do we have a release schedule for the updates to this repo?

**Comment by netzwerg** [comment]
Same here: Would like to fix a confusing copy/paste error in an example (`What's New | TypeScript 3.3`), but my hands are tied. What should I do, @DanielRosenwasser ?

**Comment by DanielRosenwasser** [comment]
Should be up to date

**Comment by salomvary** [comment]
@DanielRosenwasser seems outdated again...
