### ISSUE TITLE
broken link in `3.5 (May 2019)` roadmap

### ISSUE THREAD

**Issue by vvakame** [microsoft/TypeScript-wiki#213]
https://github.com/Microsoft/TypeScript/wiki/Roadmap#35-may-2019

`--noEmitOnError with --isolatedModules` link

actual: `https://github.com/microsoft/TypeScript/issues/310430`
expected: `https://github.com/microsoft/TypeScript/issues/31043`

**Comment by orta** [comment]
Fixed, thanks!
