### ISSUE TITLE
What's new page is too big to render

### ISSUE THREAD

**Issue by jasongrout** [microsoft/TypeScript-wiki#226]
I'm seeing this error when going to https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript

<img width="1071" alt="Screen Shot 2019-09-16 at 11 43 06 AM" src="https://user-images.githubusercontent.com/192614/64984812-6e512e80-d878-11e9-9676-987114b07db7.png">

**Comment by orta** [comment]
Ouch, this will get switched out into the site in time. 

For now I'll break this into 3.x vs 2.x & 1.x

**Comment by jasongrout** [comment]
Seems to be working now, even without being broken up. I'll leave this open in case you want to track work on it, though, and let you close it. Thanks!

**Comment by cramhead** [comment]
It's not rendering today October 3, 2019

**Comment by jasongrout** [comment]
> It's not rendering today October 3, 2019

I'm seeing the issue again too.

**Comment by orta** [comment]
I've updated it to point to the website equivalent now 👍
