### ISSUE TITLE
"What's new in TypeScript" wiki permalinks broken

### ISSUE THREAD

**Issue by jcalz** [microsoft/TypeScript-wiki#229]
The [wiki page for What's new in TypeScript](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript) is now gone/moved as it got too big for Github to render(#226).  That makes sense, but now all the bazillion links (like [this one for `readonly` tuples](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#readonly-tuples)) I and others have added to answers/comments on StackOverflow questions  are broken.  Would it be possible for the wiki page to be edited to preserve the existing permalinks?  I mean, even if the old link points to a nothing but another link to the same content hosted elsewhere (e.g., [pointing to an old revision](https://github.com/microsoft/TypeScript/wiki/What's-new-in-TypeScript/181ee76e7a8a5160dfd3ca7c334113d5955a1161#readonly-tuples)) so that the user has to click twice, it's better than just the current "this page has moved".   It would hopefully be small enough to actually render anyway.

Thoughts?  I would make a PR but I'm not sure if the code here is where the actual wiki code comes from (it seems out of date?).

**Comment by orta** [comment]
Sure, you're welcome to make a script which pulls the old ones and forwards them to the new urls?

**Comment by jcalz** [comment]
When you say "forwards", do you mean some kind of jekyll redirect thing?  I was thinking just links that point to links that point to the actual content, but if you think there's a dynamic solution, let me know.

**Comment by orta** [comment]
Yeah, just forwarding links to the site I'm afraid (so a 2nd click) - GitHub wouldn't allow any sort of auto-redirection from the markdown alas :-/

**Comment by jcalz** [comment]
Uh, okay, I have something.  I'm not sure if the code in this repo is close enough to the actual wiki content for the diff in the PR to be useful.
