### ISSUE TITLE
[Documentation] Example in breaking changes doc is confusing.

### ISSUE THREAD

**Issue by avik-so** [microsoft/TypeScript-wiki#235]
https://github.com/microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#contextual-return-types-flow-in-as-contextual-argument-types

In the documentation it lists the "broken" version as:

```
function isEven(prom: Promise<number>): Promise<{ success: boolean }> {
    return prom.then<{success: boolean}>((x) => {
        return x % 2 === 0 ?
            { success: true } :
            Promise.resolve({ success: false });
    });
}
```
The work around is listed as:

```
function isEven(prom: Promise<number>): Promise<{ success: boolean }> {
    //               vvvvvvvvvvvvvvvvvv
    return prom.then<{success: boolean}>((x) => {
           return x % 2 === 0 ?
            { success: true } :
            Promise.resolve({ success: false });
    });
}
```

Both versions of the code are the same.

**Comment by orta** [comment]
I'm struggling to [reproduce what the old code](http://www.typescriptlang.org/play/index.html?ts=3.3.3#code/GYVwdgxgLglg9mABDAzgUQG4FMwAoAOATnALYBciACsSalgDxggkBGWhAfAJSIDeAUIiGJCWKCEJIipAHRQAFjly4AHjwC8HPoOG7R4yYhWIApIgBMiddcQAGRAH4+iFCAgQsKFBSiEQWRABfRAoqGjoZURQ4ABtsXF4XNw8vCmAAQxiUAMCuAG4dIVyCwP5+CAQUKER0q2R0bDxqUgio2PiAFnMuLiA) could have looked like (though I can see it in my head) and can't find the PR that introduced it. Any ideas?

**Comment by avik-so** [comment]
@orta  set the version of typescript to 3.5 and the error shows up with the code you wrote.
