### ISSUE TITLE
Broken links on Wiki Home Page

### ISSUE THREAD

**Issue by hantatsang** [microsoft/TypeScript-wiki#273]
2 links on the home page are broken:

```markdown
- [Debugging TypeScript problems](./debugging)
- [Wanting to contribute to the TypeScript codebase or to understand the compiler](./learn-the-compiler)
```

Those links are:

- https://github.com/microsoft/TypeScript/wiki/debugging
- https://github.com/microsoft/TypeScript/wiki/learn-the-compiler

**Comment by orta** [comment]
Fixed!
