### ISSUE TITLE
Add info about using external .d.ts files to the tsconfig.json page

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-wiki#35]
From @DeanB2015's issue at https://github.com/Microsoft/TypeScript/issues/5095:

> https://github.com/Microsoft/TypeScript/wiki/tsconfig.json has great information.  Would be nice to see a `d.ts` in the files element in `Using the "files" property example.  It would demonstrate how d.ts files can be used instead of  reference path="angular2/angular2.d.ts" />   ???
> 
> Example:
> 
> "typings/tsd.d.ts"
> "angular2/angular2.d.ts"
> .....

**Comment by DanielRosenwasser** [comment]
@weswigham you might have some useful insight here.

**Comment by orta** [comment]
My gut says this is less important in the `@types` world
