### ISSUE TITLE
Confusing line in the `this` section of 2.0

### ISSUE THREAD

**Issue by styfle** [Microsoft/TypeScript-wiki#79]
Under the `this` section in 2.0 there is a line that says the following:

```
That means that this is of type Deck now, not any, so --noImplicitThis will not cause any errors.
```

Where is `Deck` even mentioned? It seems out of place.

**Comment by mhegazy** [comment]
Sorry that is wrong. should be fixed in https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript now.
