### ISSUE TITLE
Delete extra text on Specifying the type of this for functions section

### ISSUE THREAD

**Issue by Alexisvt** [Microsoft/TypeScript-wiki#80]
On *Specifying the type of this for functions* section in What's-new-in-TypeScript.md file, there are extra text under the first example of the section. The extra text is this:

> That means that this is of type Deck now, not any, so --noImplicitThis will not cause any errors.

This text doesn't appear on the wiki's page of TypeScript Repo.

**Comment by mhegazy** [comment]
should be fixed by https://github.com/Microsoft/TypeScript-wiki/commit/b4727b0a43ac831dd723ccde7dd00df78340c8f9
